xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    PRCP(mm/day)_maurer:
      dims: []
      attrs: {}
      data: 9.23945426940918
    PRCP(mm/day)_nldas:
      dims: []
      attrs: {}
      data: 10.343779563903809
    QObs(mm/d):
      dims: []
      attrs: {}
      data: 6.60306453704834
    prcp(mm/day)_daymet:
      dims: []
      attrs: {}
      data: 9.447080612182617
    srad(W/m2)_daymet:
      dims: []
      attrs: {}
      data: 152.09239196777344
    tmax(C)_daymet:
      dims: []
      attrs: {}
      data: 8.656181335449219
    tmin(C)_daymet:
      dims: []
      attrs: {}
      data: 6.311609268188477
    vp(Pa)_daymet:
      dims: []
      attrs: {}
      data: 289.32110595703125
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    PRCP(mm/day)_maurer:
      dims: []
      attrs: {}
      data: 4.975955963134766
    PRCP(mm/day)_nldas:
      dims: []
      attrs: {}
      data: 4.633057594299316
    QObs(mm/d):
      dims: []
      attrs: {}
      data: 3.8750627040863037
    prcp(mm/day)_daymet:
      dims: []
      attrs: {}
      data: 5.081298828125
    srad(W/m2)_daymet:
      dims: []
      attrs: {}
      data: 296.5553283691406
    tmax(C)_daymet:
      dims: []
      attrs: {}
      data: 11.781225204467773
    tmin(C)_daymet:
      dims: []
      attrs: {}
      data: 1.5917052030563354
    vp(Pa)_daymet:
      dims: []
      attrs: {}
      data: 698.9522094726562
